### ISSUE TITLE
Error chapter14 

### ISSUE THREAD

**Issue by Theanalyst152** [mfenner1/mlwpy_code#3] opened 2020-09-27 18:51 UTC
#error ValueError: Buffer dtype mismatch, expected 'float' but got 'double'

for cat in use_cats:
    test = image_to_example((cat, 12), translator)
    print(svc.predict(test))

**Comment by mfenner1** [comment] 2020-11-05 13:53
Thank you for reporting this!  Did that error get thrown on the `test=` line or the `print` line?

**Comment by mfenner1** [comment] 2020-11-06 15:41
Unable to reproduce this with either the old code or the new code that I'm updating for Nov 2020 current packages.  Closing.  My guess is there is some mis-alignment between versions of software installed (for example, numpy, opencv, pandas).  Unfortunately, maintain compatibility across upgrade cycles can be more difficult than any of us would like.

**Closed as completed by mfenner1** 2020-11-06 15:41 UTC
